version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
#      - MONGODB_URL=mongodb://mongo_user:mongo_password@mongo:27017/appdb?authSource=appdb
      - MONGODB_URL=mongodb://mongo_user:mongo_password@mongo:27017/
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_password